const UPDATE_GAME = 'UPDATE_GAME';
const CREATE_GAME = 'CREATE_GAME';
const UPDATE_PLAYER = 'UPDATE_PLAYER';
const CREATE_PLAYER = 'CREATE_PLAYER';
const UPDATE_PLAYERX = 'UPDATE_PLAYERX';
const UPDATE_PLAYERY = 'UPDATE_PLAYERY';

export {
  UPDATE_GAME,
  CREATE_GAME,
  UPDATE_PLAYER,
  CREATE_PLAYER,
  UPDATE_PLAYERX,
  UPDATE_PLAYERY,
};
